apiVersion: apps/v1
kind: Deployment
metadata:
  name: caryyu-app
spec:
  selector:
    matchLabels:
      app: caryyu-app
  replicas: 1
  template:
    metadata:
      labels:
        app: caryyu-app
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: book_store
        - name: POSTGRES_PASSWORD
          value: postgres
        image: postgres:14
        imagePullPolicy: IfNotPresent
        name: db
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
      - name: app
        image: caryyu/bookstore-apiserver:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: caryyu-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: caryyu-app

